import { Router } from 'express';
import authMiddleware from '../middleware/authMiddleware.js';
import { getBadges, createBadge, updateBadge, deleteBadge, getMyBadges } from '../controllers/badgeController.js';
const router = Router();
router.get('/', authMiddleware, getBadges);
router.get('/my', authMiddleware, getMyBadges);
router.post('/', authMiddleware, createBadge);
router.put('/:id', authMiddleware, updateBadge);
router.delete('/:id', authMiddleware, deleteBadge);
export default router;
